config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get '/' => "home#index"

  post '/reports-new' => "reports#create"

  post '/item-add' => "reports#item_add"

  post '/delete-report' => 'reports#delete_report'

  post '/add-one' => 'reports#add_one'

  post '/subtract-one' => 'reports#subtract_one'

  resources :reports, :teachers
  
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :report
end

app/models/report.rb
class Report < ActiveRecord::Base
  Paperclip.options[:command_path] = "/c/Program Files/ImageMagick-7.0.3-7-Q16/"

	belongs_to :user
	has_many :items

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reports
  
  def full_name
  	[fname, lname].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  	if current_user
  	 @reports = current_user.reports.reverse
     @users = User.all
  	end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :admin)
  end

  def account_update_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def show
		@report = Report.find(params[:id])
		@price = @report.items.sum(:price)
		@quantity = @report.items.sum(:quantity)
		@total = @price + @quantity

		@totals = []

		@report.items.each do |item|
			@totals << item.price * item.quantity
		end
	end
	
	def report_params
		params.require(:report).permit(:image)
	end

	def new
		@reports = current_user.reports.reverse
	end

	def update
		@report = Report.find(params[:id])

		@report.update(report_params)
		
		redirect_to :back
	end

	def create
		params.inspect

		user_id = current_user.id
		name = params[:name]

		Report.create(user_id: user_id,
					name:   name
					)

		redirect_to '/'
	end

	def item_add
		report = Report.find(params["report_id"])

		product_name = params[:product_name]
    	price = params[:price]
    	quantity = params[:quantity]
    
    	Item.create(report_id: 	  report.id.to_i,
    				product_name: product_name,
    				price: 		  price,
    				quantity: 	  quantity
    				)

    	redirect_to :back
	end
	def add_one
		item = Item.find(params["item_id"])
		item.quantity += 1
		item.save

  		redirect_to :back
	end
	def subtract_one
		item = Item.find(params["item_id"])
		item.quantity -= 1
		item.save

  		redirect_to :back
	end
	
	def delete_report
  	@report = Report.find(params["report_id"])
  	@report.destroy

  	redirect_to '/'
  	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

	def show
		@teacher = User.find(params[:id])
		@reports = @teacher.reports.reverse
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/index.html.erb
<body class="<%= !current_user ? 'landing' : nil %>">
	<% unless current_user %>
		<div class="log-in">
		<ul>D.I.Y. isn't Cheap.</ul>
		<ul>Keep Track of Your Purchases.</ul>
		<p><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></p>
		</div>
	<% end %>
	<% if current_user %>
	<img src="assets/images/arleigh-mitchell6.jpg">
	<div class="body">
		<% if current_user && current_user.admin == false %>
			<h2>Welcome <%= current_user.fname%> : Teacher</h2>
		<% end %>
		<% if current_user && current_user.admin == true %>
			<h2>Welcome <%= current_user.fname%> : Administrator</h2>
			<h3>Teachers:</h3>
			
		<% end %>

		<% if current_user && current_user.admin == false %>
			<h3>Your Reports: </h3><br>
			<% @reports.each do |report| %>
				<h4><%= link_to report.name, report %>
				</h4><br>
			<% end %>

		<% end %>

		<% if current_user && current_user.admin == true %>
			<% @users.sort_by(&:lname).each do |user| %>
				<h4><%= link_to user.full_name, teacher_path(user.id) %></h4><br>
			<% end %>

		<% end %>
	</div>
	<<% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Creative Costs</a>
      </div>

      <div class="collapse navbar-collapse">
        <% if current_user && current_user.admin == false %>
          <ul class="nav navbar-nav">
          <li><%= link_to "New Report", new_report_path %></li>
          </ul>
        <% end %>
        <% if current_user && current_user.admin == true %>
          <ul class="nav navbar-nav">
          <li><%= link_to "Teachers", '/' %></li>
          </ul>
        <% end %>
          <ul class="navbar-text pull-right">
    		<% if user_signed_in? %>
    		  <strong><%= current_user.fname %> | </strong>
    		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    		<% else %>
    		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    		<% end %></ul>
        
      </div>
    </div>
  </nav>
<% end %>

<% if notice %>
  </li> class="alert alert-success"><%= notice %></li>
<% end %>
<% if alert %>
  <li class="alert alert-danger"><%= alert %></li>
<% end %>

<%= yield %>

</body>
</html>

app/views/reports/new.html.erb
<img src="../assets/images/arleigh-mitchell6.jpg">
<div align="center" class="item_add">

<h2>Create New Report Here</h2>

<div class="create">
	<form action="/reports-new" method="post">
		<label class="label" for="name">Title (ex: Dec. 2016)</label><br>
		<input type="text" name="name"><br>
		<br>
		<button class="btn btn-default btn-sm" type="submit">Create Report</button>
	</form>
</div>
</div>

app/views/reports/show.html.erb
<div class="item_add">	
	<h2><%= @report.name %></h2>
	<% if current_user && current_user.admin == true %>
		<h4><%= @report.user.full_name %></h4>
	<% end %>
	<% if current_user && current_user.admin == false %>
		<form action="/item-add" method="post">
			<label class="label" for="product_name">Product</label><br>
			<input type="text" name="product_name"><br>
			<label class="label" for="quantity">Quantity</label><br>
			<input type="text" name="quantity"><br>
			<label class="label" for="price">Price</label><br>
			<input type="text" name="price"><br>
			<input type="hidden" name="report_id" value="<%= @report.id %>"><br>
			<button class="btn btn-default btn-sm" type="submit">Add Item</button>
		</form><br><br>
	<% end %>
	<div class="table-responsive">
		<table class="table">
		  <tr>
		    <th>Product</th>
		    <th>Price</th>
		    <th>Quantity</th>
		    <th>Date</th>
		    <th>Total</th>
		  </tr>
		  <% @report.items.each do |item| %>
		  <tr>
		    <td><%= item.product_name %></td>
		    <td>$ <%= item.price %></td>
		    <td><%= item.quantity %>
		    	<% if current_user && current_user.admin == false %>
				<div class="forms">
				    <form class="form" method="post" action="/add-one">
						<input type="hidden" name="item_id" value="<%= item.id %>">
						<button class="btn btn-default btn-xs" type="submit">+</button>
					</form>
					<form class="form" method="post" action="/subtract-one">
						<input type="hidden" name="item_id" value="<%= item.id %>">
						<button class="btn btn-default btn-xs" type="submit">-</button>
					</form>
				</div>
				<% end %>
			</td>
		    <td><%= item.created_at.strftime("%F") if item.created_at %></td>
		    <td>$ <%= item.price*item.quantity %></td>
		  </tr>
		  <% end %>
		</table>
	</div>
	<h3>Total: $ <%= @totals.sum %></h3><br>
	<h4><%= link_to 'Print', 'your_link_here', :onclick => 'window.print();return false;'%> 
	<% if current_user && current_user.admin == true %>
		 | <%= link_to "Back", :back %></h4>
	<% end %><br>
	<% if current_user && current_user.admin == false %>
	<form method="post" action="/delete-report">
		<input type="hidden" name="report_id" value="<%= @report.id %>">
		<br><button class="btn btn-default btn-sm" type="submit">Delete Report</button>
	</form>
	<% end %>
</div>

app/views/teachers/show.html.erb
<img src="../assets/images/arleigh-mitchell6.jpg">

<div class="body">
<h2><%= @teacher.full_name %></h2>
<% @reports.each do |report| %>
	<h4><%= link_to report.name, report %></h4><br>
<% end %>
</div>